title: MY PORTFOLIO
author: Buteya
email: buteyamasira@gmail.com
description: > This is a static site showcasing the various coding languages and coding tools I`m profecient in.

# social links
twitter_username: steve masira
github_username:  buteya

show_excerpts: true 
theme: minima
